Repository InfiniTensor/InfiniCore, pull requests merged in 2025-06, with the labels that each got.

#146 issue/142：添加rms_norm算子测例
  src/infiniop-test/include/ops.hpp
  src/infiniop-test/src/ops/rms_norm.cpp
  test/infiniop-test/test_generate/testcases/rms_norm.py
Labels: 准备好了, 类型：测试

#249 issue/228: swiglu测例0步长添加
  src/infiniop-test/src/ops/random_sample.cpp
  test/infiniop-test/test_generate/__init__.py
  test/infiniop-test/test_generate/infiniop_test.py
  test/infiniop-test/test_generate/testcases/add.py
  test/infiniop-test/test_generate/testcases/clip.py
  test/infiniop-test/test_generate/testcases/swiglu.py
Labels: 准备好了, 类型：测试

#244 issue/39 Migrate cuda causal softmax to metax
  src/infiniop/ops/causal_softmax/maca/causal_softmax_kernel.h
  src/infiniop/ops/causal_softmax/maca/causal_softmax_maca.h
  src/infiniop/ops/causal_softmax/maca/causal_softmax_maca.maca
  src/infiniop/ops/causal_softmax/operator.cc
  src/infiniop/reduce/maca/reduce.h
Labels: 类型：开发, 准备好了, 模块：算子

#245 issue/238 - Migrate cuda rearrange to metax
  src/infiniop/ops/rearrange/maca/rearrange_kernel.h
  src/infiniop/ops/rearrange/maca/rearrange_maca.h
  src/infiniop/ops/rearrange/maca/rearrange_maca.maca
  src/infiniop/ops/rearrange/operator.cc
Labels: 类型：开发, 准备好了, 模块：算子

#258 issue/36 - Migrate cuda ramdom sample to metax
  src/infiniop/ops/random_sample/maca/random_sample_kernel.h
  src/infiniop/ops/random_sample/maca/random_sample_maca.h
  src/infiniop/ops/random_sample/maca/random_sample_maca.maca
  src/infiniop/ops/random_sample/operator.cc
Labels: 类型：开发, 准备好了, 模块：算子

#274 issue/273: Fully Support `equal_nan` Option for `debug()` and `debug_all()`
  test/infiniop/libinfiniop/utils.py
Labels: 准备好了, 类型：BUG, 类型：测试

#283 issue/282: Maca CausalSoftamx精度bug
  src/infiniop/ops/causal_softmax/maca/causal_softmax_kernel.h
  test/infiniop/causal_softmax.py
Labels: 紧急！, 需要修改, 类型：BUG, 模块：算子

#62 issue/11: add random sample ascend
  src/infiniop/devices/ascend/CMakeLists.txt
  src/infiniop/devices/ascend/ascend_kernel_common.h
  src/infiniop/ops/random_sample/ascend/random_sample_aclnn.h
  src/infiniop/ops/random_sample/ascend/random_sample_kernel.cpp
  src/infiniop/ops/random_sample/ascend/randomsample_aclnn.cc
  src/infiniop/ops/random_sample/operator.cc
  test/infiniop/random_sample.py
Labels: 类型：开发, 准备好了, 模块：算子

#285 issue/137: 添加causal_softmax测例，更新readme（合并）
  scripts/python_test.py
  src/infiniop-test/include/ops.hpp
  src/infiniop-test/src/ops/causal_softmax.cpp
  test/infiniop-test/README.md
  test/infiniop-test/test_generate/testcases/causal_softmax.py
  test/infiniop/causal_softmax.py
Labels: 准备好了, 模块：算子, 类型：测试

#289 issue/288: Improve the Compatibility of the Torch Implementations
  test/infiniop/gemm.py
  test/infiniop/random_sample.py
  test/infiniop/rearrange.py
Labels: 类型：优化, 准备好了, 类型：测试
