Repository InfiniTensor/InfiniCore, pull requests merged in 2025-03, with the labels that each got.

#79 issue/78/feat: 实现 rearrange
  src/utils/rearrange.cc
  src/utils/rearrange.h
Labels: 类型：开发, 准备好了

#81 issue/78/feat: 分离 rearrange 的规划和执行以供算子复用
  src/utils/rearrange.cc
  src/utils/rearrange.h
Labels: 类型：开发, 准备好了

#83 issue/63/fix: 移除 cuda mat mul 中无意义的模板
  src/infiniop/ops/matmul/cuda/matmul_cuda.cu
Labels: 准备好了, 类型：BUG, 模块：算子

#91 issue/87/refactor: 重构 cuda handle，并修改 cpu handle 和 matmul 命名空间
  .github/workflows/build.yml
  include/infiniop.h
  include/infiniop/handle.h
  src/infiniop/devices/cpu/cpu_handle.cc
  src/infiniop/devices/cpu/cpu_handle.h
  src/infiniop/devices/cuda/common_cuda.cuh
  src/infiniop/devices/cuda/cuda_handle.cu
  src/infiniop/devices/cuda/cuda_handle.cuh
  src/infiniop/devices/cuda/cuda_handle.h
  src/infiniop/devices/handle.cc
  src/infiniop/ops/matmul/ascend/matmul_ascend.cc
  src/infiniop/ops/matmul/bang/matmul_bang.cc
  src/infiniop/ops/matmul/blas.h
  src/infiniop/ops/matmul/cpu/matmul_cpu.cc
  src/infiniop/ops/matmul/cuda/matmul_cuda.cu
  src/infiniop/ops/matmul/kunlun/matmul_kunlun.cc
  src/infiniop/ops/matmul/matmul.h
  src/infiniop/ops/matmul/operator.cc
  test/infiniop/libinfiniop/liboperators.py
  test/infiniop/libinfiniop/utils.py
  xmake.lua
  xmake/ascend.lua
  xmake/bang.lua
  xmake/cuda.lua
  xmake/kunlun.lua
Labels: 准备好了, 类型：重构, 模块：算子

#95 issue/87/feat: cublas 和 cudnn 检查并返回错误信息
  src/infiniop/devices/cuda/cuda_common.cu
  src/infiniop/devices/cuda/cuda_common.cuh
  src/infiniop/devices/cuda/cuda_handle.cu
  src/infiniop/devices/cuda/cuda_handle.cuh
  src/infiniop/ops/matmul/cuda/matmul_cuda.cu
Labels: 类型：开发, 准备好了

#101 Issue/89/bang Refactor Handle, Runtime, and Matmul Implementation for Bang
  src/infiniop/devices/bang/bang_handle.cc
  src/infiniop/devices/bang/bang_handle.h
  src/infiniop/devices/bang/common_bang.h
  src/infiniop/devices/handle.cc
  src/infiniop/ops/matmul/bang/matmul_bang.cc
  src/infinirt/bang/infinirt_bang.cc
  src/infinirt/bang/infinirt_bang.h
  src/infinirt/infinirt.cc
Labels: 准备好了, 类型：重构, 模块：运行时

#100 issue/87/feat:增加沐曦平台的handle
  src/infiniop/devices/handle.cc
  src/infiniop/devices/maca/common_maca.h
  src/infiniop/devices/maca/maca_handle.cc
  src/infiniop/devices/maca/maca_handle.h
  src/infiniop/ops/matmul/maca/matmul_maca.cc
  src/infiniop/ops/matmul/maca/matmul_maca.h
  src/infiniop/ops/matmul/operator.cc
  src/infinirt/maca/infinirt_maca.cc
  src/infinirt/maca/infinirt_maca.h
  test/infiniop/libinfiniop/utils.py
  xmake.lua
  xmake/maca.lua
Labels: 准备好了, 类型：重构

#96 issur/87/feat:修改昇腾平台的handle
  src/infiniop/devices/ascend/ascend_handle.cc
  src/infiniop/devices/ascend/ascend_handle.h
  src/infiniop/devices/ascend/common_ascend.cc
  src/infiniop/devices/ascend/common_ascend.h
  src/infiniop/devices/ascend/tensor_aclnn.cc
  src/infiniop/devices/ascend/tensor_aclnn.h
  src/infiniop/devices/handle.cc
  src/infiniop/ops/matmul/ascend/matmul_ascend.cc
Labels: 准备好了, 类型：重构

#99 issue/87: restruct kunlun handle
  src/infiniop/devices/handle.cc
  src/infiniop/devices/kunlun/common_kunlun.h
  src/infiniop/devices/kunlun/kunlun_handle.cc
  src/infiniop/devices/kunlun/kunlun_handle.h
  src/infiniop/ops/matmul/kunlun/matmul_kunlun.cc
  src/infinirt/kunlun/infinirt_kunlun.cc
  src/infinirt/kunlun/infinirt_kunlun.h
  xmake.lua
  xmake/cpu.lua
  xmake/kunlun.lua
Labels: 准备好了, 类型：重构, 模块：运行时

#51 issue/48: random sample 算子 - CPU
  .github/workflows/build.yml
  include/infiniop/ops/random_sample.h
  src/infiniop/ops/random_sample/cpu/random_sample_cpu.cc
  src/infiniop/ops/random_sample/cpu/random_sample_cpu.h
  src/infiniop/ops/random_sample/operator.cc
  src/infiniop/ops/random_sample/random_sample.h
  src/utils/check.h
  test/infiniop/random_sample.py
Labels: 类型：开发, 准备好了, 模块：算子

#94 issue/68 测试框架，matmul测例生成
  .github/workflows/build.yml
  .gitignore
  src/infiniop-test/include/file_mapping.hpp
  src/infiniop-test/include/gguf.hpp
  src/infiniop-test/include/ops.hpp
  src/infiniop-test/include/tensor.hpp
  src/infiniop-test/include/test.hpp
  src/infiniop-test/include/utils.hpp
  src/infiniop-test/src/file_mapping.cpp
  src/infiniop-test/src/gguf.cpp
  src/infiniop-test/src/main.cpp
  src/infiniop-test/src/ops/matmul.cpp
  src/infiniop-test/src/tensor.cpp
  src/infiniop-test/src/test.cpp
  src/utils-test/test_rearrange.cc
  src/utils/rearrange.cc
  test/infiniop-test/README.md
  test/infiniop-test/test_generate/__init__.py
  test/infiniop-test/test_generate/infiniop_test.py
  test/infiniop-test/test_generate/testcases/__init__.py
  test/infiniop-test/test_generate/testcases/matmul.py
  xmake.lua
  xmake/test.lua
Labels: 准备好了, 模块：算子, 类型：文档, 类型：测试

#105 issue/6 添加cuda通用reduce模块，实现rmsnorm cuda算子
  include/infinicore.h
  src/infiniop/devices/cuda/cuda_common.cuh
  src/infiniop/ops/rms_norm/cuda/rms_norm_cuda.cu
  src/infiniop/ops/rms_norm/cuda/rms_norm_cuda.cuh
  src/infiniop/ops/rms_norm/cuda/rms_norm_kernel.cuh
  src/infiniop/ops/rms_norm/operator.cc
  src/infiniop/ops/rms_norm/rms_norm.h
  src/infiniop/reduce/cuda/reduce.cuh
Labels: 类型：开发, 准备好了, 模块：算子

#98 issue/97/feat: 实现 rearrange cpu
  include/infiniop/ops/rearrange.h
  src/infiniop/ops/rearrange/cpu/rearrange_cpu.cc
  src/infiniop/ops/rearrange/cpu/rearrange_cpu.h
  src/infiniop/ops/rearrange/operator.cc
  src/infiniop/ops/rearrange/rearrange.h
Labels: 类型：开发, 准备好了, 模块：算子

#107 issue/103: 添加并修补matmul测例
  src/infiniop-test/src/ops/matmul.cpp
  src/infiniop-test/src/tensor.cpp
  src/infiniop-test/src/test.cpp
  test/infiniop-test/test_generate/testcases/matmul.py
Labels: 需要修改, 模块：算子, 类型：测试

#118 issue/117 修复infinirt.h安装路径
  include/infiniop/handle.h
  include/infiniop/operator_descriptor.h
  include/infiniop/ops/add.h
  include/infiniop/ops/attention.h
  include/infiniop/ops/avg_pool.h
  include/infiniop/ops/causal_softmax.h
  include/infiniop/ops/conv.h
  include/infiniop/ops/expand.h
  include/infiniop/ops/gemm.h
  include/infiniop/ops/global_avg_pool.h
  include/infiniop/ops/max_pool.h
  include/infiniop/ops/mlp.h
  include/infiniop/ops/random_sample.h
  include/infiniop/ops/rearrange.h
  include/infiniop/ops/relu.h
  include/infiniop/ops/rms_norm.h
  include/infiniop/ops/rotary_embedding.h
  include/infiniop/ops/swiglu.h
  xmake.lua
Labels: 紧急！, 类型：BUG, 模块：算子, 模块：运行时

#109 issue/108: 添加random sample算子测例
  src/infiniop-test/include/ops.hpp
  src/infiniop-test/src/ops/random_sample.cpp
  src/infiniop/tensor_descriptor.cc
  test/infiniop-test/test_generate/testcases/random_sample.py
  test/infiniop/random_sample.py
Labels: 准备好了, 模块：算子, 类型：测试

#110 issue/3: causal_softmax的CPU重构
  src/infiniop/ops/causal_softmax/causal_softmax.h
  src/infiniop/ops/causal_softmax/cpu/causal_softmax_cpu.cc
  src/infiniop/ops/causal_softmax/cpu/causal_softmax_cpu.h
  src/infiniop/ops/causal_softmax/operator.cc
  src/infiniop/reduce/cpu/reduce.cc
  src/infiniop/reduce/cpu/reduce.h
  test/infiniop/causal_softmax.py
  xmake/cpu.lua
Labels: 需要修改, 类型：重构, 模块：算子

#124 issue/123 修复昇腾平台编译utils缺少fpic选项问题
  xmake.lua
  xmake/cpu.lua
Labels: 紧急！, 准备好了, 类型：BUG

#47 issue/46: swiglu 算子 - CPU
  .github/workflows/build.yml
  src/infiniop/binary/binary.h
  src/infiniop/binary/cpu/binary_cpu.h
  src/infiniop/devices/cpu/common_cpu.cc
  src/infiniop/devices/cpu/common_cpu.h
  src/infiniop/ops/swiglu/cpu/swiglu_cpu.cc
  src/infiniop/ops/swiglu/cpu/swiglu_cpu.h
  src/infiniop/ops/swiglu/operator.cc
  src/infiniop/tensor.h
  src/infiniop/tensor_descriptor.cc
  src/utils/check.h
  test/infiniop/swiglu.py
  xmake/cpu.lua
Labels: 准备好了, 模块：算子
