Repository InfiniTensor/InfiniCore, pull requests merged in 2025-07, with the labels that each got.

#255 issue/254: 添加算子在CPU和CUDA上对BF16的支持，并增加相应的测试代码
  src/infiniop/devices/cuda/cuda_kernel_common.cuh
  src/infiniop/elementwise/cpu/elementwise_cpu.h
  src/infiniop/ops/causal_softmax/cpu/causal_softmax_cpu.cc
  src/infiniop/ops/causal_softmax/cuda/causal_softmax_cuda.cu
  src/infiniop/ops/causal_softmax/info.h
  src/infiniop/ops/gemm/cpu/gemm_cpu.cc
  src/infiniop/ops/gemm/cuda/gemm_cuda.cu
  src/infiniop/ops/random_sample/cpu/random_sample_cpu.cc
  src/infiniop/ops/random_sample/cuda/random_sample_cuda.cu
  src/infiniop/ops/random_sample/cuda/random_sample_kernel.cuh
  src/infiniop/ops/random_sample/info.h
  src/infiniop/ops/random_sample/random_sample.h
  src/infiniop/ops/rms_norm/cpu/rms_norm_cpu.cc
  src/infiniop/ops/rms_norm/cuda/rms_norm_cuda.cu
  src/infiniop/ops/rms_norm/info.h
  src/infiniop/ops/rope/cpu/rope_cpu.cc
  src/infiniop/ops/rope/cuda/rope_cuda.cu
  src/infiniop/ops/rope/cuda/rope_cuda_kernel.cuh
  src/infiniop/ops/rope/rope.h
  src/infiniop/ops/swiglu/cpu/swiglu_cpu.cc
  src/infiniop/ops/swiglu/cuda/swiglu_cuda.cu
  src/infiniop/ops/swiglu/cuda/swiglu_cuda_internal.cuh
  src/infiniop/reduce/cpu/reduce.cc
  src/infiniop/reduce/cpu/reduce.h
  src/utils/custom_types.cc
  src/utils/custom_types.h
  test/infiniop/causal_softmax.py
  test/infiniop/gemm.py
  test/infiniop/libinfiniop/utils.py
  test/infiniop/random_sample.py
  test/infiniop/rms_norm.py
  test/infiniop/rope.py
  test/infiniop/swiglu.py
Labels: 紧急！, 准备好了, 模块：算子

#297 issue/296 isContigous tolerates length 1 dimension
  src/infiniop/ops/attention/operator.cc
  src/infiniop/ops/rope/rope.h
  src/infiniop/tensor.h
  src/infiniop/tensor_descriptor.cc
Labels: 紧急！, 准备好了, 类型：BUG, 模块：算子

#159 issue/158/feat: 支持天数
  README.md
  src/infiniop/devices/cuda/cuda_common.cu
  src/infiniop/devices/cuda/cuda_kernel_common.cuh
  src/infiniop/ops/causal_softmax/cuda/causal_softmax_cuda.cu
  src/infiniop/ops/clip/cuda/clip_cuda_internal.cuh
  src/infiniop/ops/gemm/cuda/gemm_cuda.cu
  src/infiniop/ops/gemm/info.h
  src/infiniop/ops/rearrange/cuda/rearrange_kernel.cuh
  src/infiniop/ops/rms_norm/cuda/rms_norm_cuda.cu
  src/infinirt/cuda/infinirt_cuda.cu
  xmake.lua
  xmake/iluvatar.lua
Labels: 紧急！, 类型：开发, 需要修改, 模块：运行时

#305 issue/304 fix clip
  scripts/python_test.py
  src/infiniop/ops/clip/cuda/clip_cuda_internal.cuh
  test/infiniop/clip.py
  test/infiniop/libinfiniop/utils.py
  xmake/cuda.lua
Labels: 准备好了, 类型：BUG, 模块：算子

#308 issue/307 unify test tensor creation in pytorch tests
  include/infiniop.h
  include/infiniop/ops/avg_pool.h
  include/infiniop/ops/expand.h
  include/infiniop/ops/global_avg_pool.h
  include/infiniop/ops/max_pool.h
  include/infiniop/ops/mlp.h
  scripts/python_test.py
  test/infiniop/add.py
  test/infiniop/attention.py
  test/infiniop/avg_pool.py
  test/infiniop/causal_softmax.py
  test/infiniop/clip.py
  test/infiniop/expand.py
  test/infiniop/gemm.py
  test/infiniop/global_avg_pool.py
  test/infiniop/libinfiniop/__init__.py
  test/infiniop/libinfiniop/datatypes.py
  test/infiniop/libinfiniop/devices.py
  test/infiniop/libinfiniop/liboperators.py
  test/infiniop/libinfiniop/op_register.py
  test/infiniop/libinfiniop/structs.py
  test/infiniop/libinfiniop/utils.py
  test/infiniop/max_pool.py
  test/infiniop/mlp.py
  test/infiniop/mul.py
  test/infiniop/random_sample.py
  test/infiniop/rearrange.py
  test/infiniop/rms_norm.py
  test/infiniop/rope.py
  test/infiniop/sub.py
  test/infiniop/swiglu.py
Labels: 紧急！, 准备好了, 类型：重构, 模块：算子, 类型：测试

#233 issue/232: 接入九齿
  scripts/build_ntops.py
  scripts/format.py
  src/infiniop/ninetoothed/build.py
  xmake/cuda.lua
Labels: 紧急！, 类型：开发, 准备好了, 类型：重构, 模块：算子

#315 issue/314 修复 nvidia 上编译和测试问题
  src/infiniccl/cuda/infiniccl_cuda.h
  src/infiniop/devices/cuda/cuda_common.cu
  src/infiniop/devices/cuda/cuda_common.cuh
  src/infiniop/devices/cuda/cuda_handle.cuh
  src/infiniop/devices/cuda/cuda_kernel_common.cuh
  src/infiniop/devices/handle.cc
  src/infiniop/ops/add/operator.cc
  src/infiniop/ops/causal_softmax/cuda/causal_softmax_kernel.cuh
  src/infiniop/ops/causal_softmax/operator.cc
  src/infiniop/ops/clip/operator.cc
  src/infiniop/ops/gemm/operator.cc
  src/infiniop/ops/mul/operator.cc
  src/infiniop/ops/random_sample/operator.cc
  src/infiniop/ops/rearrange/operator.cc
  src/infiniop/ops/rms_norm/operator.cc
  src/infiniop/ops/rope/operator.cc
  src/infiniop/ops/sub/operator.cc
  src/infiniop/ops/swiglu/operator.cc
  src/infinirt/cuda/infinirt_cuda.cuh
  test/infiniop/rope.py
  xmake.lua
  xmake/cuda.lua
Labels: 紧急！, 准备好了, 类型：BUG

#317 issue/316 添加开发者手册
  DEV.md
  README.md
  test/infiniop-test/README.md
Labels: 类型：文档

#327 issue/158/feat: 编译天数 ccl
  xmake.lua
  xmake/iluvatar.lua
Labels: 类型：开发, 准备好了, 模块：算子, 模块：通信

#326 issue/291/fix: 改正 conv 中的编译错误和 xmake 中的一些问题
  src/infiniop/ops/conv/nvidia/conv_nvidia.cu
  xmake.lua
  xmake/nvidia.lua
Labels: 紧急！, 准备好了, 类型：重构

#328 issue/158/refactor: 分离天数和英伟达的算子定义
  src/infiniccl/cuda/infiniccl_cuda.h
  src/infiniop/devices/handle.cc
  src/infiniop/devices/nvidia/nvidia_common.cu
  src/infiniop/devices/nvidia/nvidia_handle.h
  src/infiniop/devices/nvidia/nvidia_kernel_common.cuh
  src/infiniop/ops/add/operator.cc
  src/infiniop/ops/causal_softmax/operator.cc
  src/infiniop/ops/clip/cuda/kernel.cuh
  src/infiniop/ops/clip/operator.cc
  src/infiniop/ops/conv/nvidia/conv_nvidia.cu
  src/infiniop/ops/conv/operator.cc
  src/infiniop/ops/gemm/nvidia/gemm_nvidia.cu
  src/infiniop/ops/gemm/operator.cc
  src/infiniop/ops/mul/operator.cc
  src/infiniop/ops/random_sample/operator.cc
  src/infiniop/ops/rearrange/operator.cc
  src/infiniop/ops/rms_norm/operator.cc
  src/infiniop/ops/rope/operator.cc
  src/infiniop/ops/sub/operator.cc
  src/infiniop/ops/swiglu/operator.cc
  src/infinirt/cuda/infinirt_cuda.cu
  src/infinirt/cuda/infinirt_cuda.cuh
  test/infiniop/libinfiniop/utils.py
  xmake.lua
  xmake/iluvatar.lua
Labels: 紧急！, 准备好了, 类型：重构

#329 issue/158/fix: Update handle.cc
  src/infiniop/devices/handle.cc
Labels: 紧急！, 准备好了, 类型：BUG

#339 issue/112: infinirt测试框架
  .github/workflows/build.yml
  src/infinirt-test/main.cc
  src/infinirt-test/test.cc
  src/infinirt-test/test.h
  src/infinirt/infinirt.cc
  xmake/test.lua
Labels: 准备好了, 模块：运行时, 类型：测试
