Repository InfiniTensor/InfiniCore, pull requests merged in 2025-09, with the labels that each got.

#424 issue/423: Improve the Precision of the PyTorch Implementation of `rms_norm`
  test/infiniop/rms_norm.py
Labels: 准备好了, 类型：BUG, 类型：测试

#432 Issue/427 - 修改和添加MoE所需的算子, sigmoid, topksoftmax, topkrouter.
  include/infiniop.h
  include/infiniop/ops/sigmoid.h
  include/infiniop/ops/topkrouter.h
  include/infiniop/ops/topksoftmax.h
  scripts/python_test.py
  src/infiniccl/cuda/infiniccl_cuda.cu
  src/infiniop-test/include/ops.hpp
  src/infiniop-test/src/ops/sigmoid.cpp
  src/infiniop-test/src/ops/topkrouter.cpp
  src/infiniop-test/src/ops/topksoftmax.cpp
  src/infiniop/ops/dequantize/info.h
  src/infiniop/ops/sigmoid/cpu/sigmoid_cpu.cc
  src/infiniop/ops/sigmoid/cpu/sigmoid_cpu.h
  src/infiniop/ops/sigmoid/cuda/kernel.cuh
  src/infiniop/ops/sigmoid/nvidia/sigmoid_nvidia.cu
  src/infiniop/ops/sigmoid/nvidia/sigmoid_nvidia.cuh
  src/infiniop/ops/sigmoid/operator.cc
  src/infiniop/ops/topkrouter/cpu/topkrouter_cpu.cc
  src/infiniop/ops/topkrouter/cpu/topkrouter_cpu.h
  src/infiniop/ops/topkrouter/cuda/kernel.cuh
  src/infiniop/ops/topkrouter/info.h
  src/infiniop/ops/topkrouter/nvidia/topkrouter_nvidia.cu
  src/infiniop/ops/topkrouter/nvidia/topkrouter_nvidia.cuh
  src/infiniop/ops/topkrouter/operator.cc
  src/infiniop/ops/topkrouter/topkrouter.h
  src/infiniop/ops/topksoftmax/cpu/topksoftmax_cpu.cc
  src/infiniop/ops/topksoftmax/cpu/topksoftmax_cpu.h
  src/infiniop/ops/topksoftmax/cuda/kernel.cuh
  src/infiniop/ops/topksoftmax/info.h
  src/infiniop/ops/topksoftmax/nvidia/topksoftmax_nvidia.cu
  src/infiniop/ops/topksoftmax/nvidia/topksoftmax_nvidia.cuh
  src/infiniop/ops/topksoftmax/operator.cc
  src/infiniop/ops/topksoftmax/topksoftmax.h
  test/infiniop-test/test_generate/testcases/sigmoid.py
  test/infiniop-test/test_generate/testcases/topkrouter.py
  test/infiniop-test/test_generate/testcases/topksoftmax.py
  test/infiniop/libinfiniop/op_register.py
  test/infiniop/sigmoid.py
  test/infiniop/topkrouter.py
  test/infiniop/topksoftmax.py
Labels: 类型：开发, 模块：算子

#429 Issue/428: Merge `rope_v2` into `rope`
  include/infiniop.h
  include/infiniop/ops/rope.h
  include/infiniop/ops/rope_v2.h
  src/infiniop-test/src/ops/rope.cpp
  src/infiniop/ops/rope/ascend/rope_ascend.cc
  src/infiniop/ops/rope/bang/rope_bang.mlu
  src/infiniop/ops/rope/cpu/rope_cpu.cc
  src/infiniop/ops/rope/cuda/kernel.cuh
  src/infiniop/ops/rope/kunlun/rope_kunlun.xpu
  src/infiniop/ops/rope/metax/rope_metax.maca
  src/infiniop/ops/rope/moore/rope_kernel_moore.h
  src/infiniop/ops/rope/moore/rope_moore.mu
  src/infiniop/ops/rope/nvidia/rope_nvidia.cu
  src/infiniop/ops/rope/operator.cc
  src/infiniop/ops/rope/rope.h
  src/infiniop/ops/rope_v2/ascend/rope_ascend.cc
  src/infiniop/ops/rope_v2/ascend/rope_ascend.h
  src/infiniop/ops/rope_v2/ascend/rope_ascend_kernel.cpp
  src/infiniop/ops/rope_v2/bang/rope_bang.h
  src/infiniop/ops/rope_v2/bang/rope_bang.mlu
  src/infiniop/ops/rope_v2/bang/rope_bang_kernel.mlu
  src/infiniop/ops/rope_v2/cpu/rope_v2_cpu.cc
  src/infiniop/ops/rope_v2/cpu/rope_v2_cpu.h
  src/infiniop/ops/rope_v2/cuda/kernel.cuh
  src/infiniop/ops/rope_v2/metax/rope_metax.h
  src/infiniop/ops/rope_v2/metax/rope_metax.maca
  src/infiniop/ops/rope_v2/nvidia/rope_v2_nvidia.cu
  src/infiniop/ops/rope_v2/nvidia/rope_v2_nvidia.cuh
  src/infiniop/ops/rope_v2/operator.cc
  src/infiniop/ops/rope_v2/rope_v2.h
  test/infiniop-test/test_generate/testcases/rope.py
  test/infiniop/libinfiniop/op_register.py
  test/infiniop/rope.py
  test/infiniop/rope_v2.py
Labels: 准备好了, 类型：重构, 模块：算子

#438 issue/434 hccl support bf16
  src/infiniccl-test/infiniccl_test.cpp
  src/infiniccl/metax/infiniccl_metax.cc
  src/infiniop/ops/softplus/metax/softplus_metax.h
  src/infiniop/ops/softplus/metax/softplus_metax.maca
Labels: 准备好了, 模块：通信

#437 issue/436：修补昆仑芯端到端推理遇到的问题
  src/infiniop/devices/kunlun/kunlun_kernel_common.h
  src/infiniop/ops/gemm/kunlun/gemm_kunlun.cc
  src/infiniop/ops/random_sample/kunlun/random_sample_kunlun.xpu
  src/infiniop/ops/rope/kunlun/rope_kunlun.xpu
  test/infiniop/attention.py
  test/infiniop/libinfiniop/utils.py
  test/infiniop/rearrange.py
  test/infiniop/rms_norm.py
Labels: 准备好了, 类型：BUG

#462 issue/434 - added bf16 support for Cambricon MLU
  src/infiniccl/cambricon/infiniccl_cambricon.cc
Labels: 类型：开发, 准备好了, 模块：通信

#460 Issue/459
  src/infiniop/ops/rms_norm/bang/rms_norm_bang.mlu
  test/infiniop/rms_norm.py
Labels: 类型：优化, 准备好了, 类型：BUG, 模块：算子
