Repository InfiniTensor/InfiniCore, pull requests merged in 2025-05, with the labels that each got.

#210 Issue/209 elementwise kunlun
  src/infiniop/devices/kunlun/kunlun_common.h
  src/infiniop/devices/kunlun/kunlun_handle.h
  src/infiniop/devices/kunlun/kunlun_kernel_common.h
  src/infiniop/devices/kunlun/kunlun_kernel_dtype.h
  src/infiniop/elementwise/kunlun/elementwise_kunlun.h
  src/infiniop/elementwise/kunlun/elementwise_kunlun_api.h
  src/infiniop/elementwise/kunlun/elementwise_kunlun_kernel.h
  src/infiniop/ops/gemm/kunlun/gemm_kunlun.cc
  src/infiniop/ops/rms_norm/kunlun/rms_norm_kernel.xpu
  src/infiniop/ops/swiglu/kunlun/swiglu_kunlun.cc
  src/infiniop/ops/swiglu/kunlun/swiglu_kunlun.h
  src/infiniop/ops/swiglu/kunlun/swiglu_kunlun_internal.xpu
  src/infiniop/ops/swiglu/operator.cc
  src/infiniop/reduce/kunlun/reduce_kunlun.h
  src/infinirt/infinirt.cc
  test/infiniop/attention.py
  test/infiniop/avg_pool.py
  test/infiniop/causal_softmax.py
  test/infiniop/conv.py
  test/infiniop/expand.py
  test/infiniop/gemm.py
  test/infiniop/global_avg_pool.py
  test/infiniop/libinfiniop/utils.py
  test/infiniop/max_pool.py
  test/infiniop/mlp.py
  test/infiniop/random_sample.py
  test/infiniop/rearrange.py
  test/infiniop/relu.py
  test/infiniop/rms_norm.py
  test/infiniop/rope.py
Labels: 类型：开发, 准备好了, 模块：算子

#186 issue/148: 添加swiglu算子测例
  src/infiniop-test/include/ops.hpp
  src/infiniop-test/src/ops/swiglu.cpp
  test/infiniop-test/test_generate/testcases/swiglu.py
Labels: 准备好了, 类型：测试

#192 issue/191/docs: 规范 random sample 算子构造过程，添加 cuda 接口
  README.md
  src/infiniop/ops/random_sample/cpu/random_sample_cpu.cc
  src/infiniop/ops/random_sample/cuda/random_sample_cuda.cu
  src/infiniop/ops/random_sample/cuda/random_sample_cuda.cuh
  src/infiniop/ops/random_sample/cuda/random_sample_kernel.cuh
  src/infiniop/ops/random_sample/info.h
  src/infiniop/ops/random_sample/operator.cc
  src/infiniop/ops/random_sample/random_sample.h
Labels: 类型：开发, 需要修改, 模块：算子

#175 issue/174: Rearrange ASCEND
  src/infiniop/devices/ascend/common_ascend.cc
  src/infiniop/ops/causal_softmax/ascend/causal_softmax_aclnn.cc
  src/infiniop/ops/rearrange/ascend/rearrange_ascend.cc
  src/infiniop/ops/rearrange/ascend/rearrange_ascend.h
  src/infiniop/ops/rearrange/operator.cc
  src/infiniop/ops/rms_norm/ascend/rms_norm_aclnn.cc
  src/infiniop/ops/swiglu/operator.cc
  test/infiniop/causal_softmax.py
  test/infiniop/libinfiniop/utils.py
Labels: 紧急！, 类型：开发, 准备好了, 模块：算子

#139 feat: 添加昇腾swiglu算子
  src/infiniop/devices/ascend/CMakeLists.txt
  src/infiniop/devices/ascend/ascend_kernel_common.h
  src/infiniop/ops/causal_softmax/ascend/causal_softmax_ascend.cc
  src/infiniop/ops/causal_softmax/ascend/causal_softmax_ascend.h
  src/infiniop/ops/causal_softmax/operator.cc
  src/infiniop/ops/swiglu/ascend/swiglu_ascend.cc
  src/infiniop/ops/swiglu/ascend/swiglu_ascend.h
  src/infiniop/ops/swiglu/ascend/swiglu_ascend_kernel.cpp
  src/infiniop/ops/swiglu/operator.cc
  xmake/ascend.lua
Labels: 紧急！, 类型：开发, 准备好了, 模块：算子

#217 issue/216 - Fixed Enum Camparison in util.py
  test/infiniop/libinfiniop/utils.py
Labels: 准备好了, 类型：BUG, 类型：测试

#220 issue/219: 添加attention算子
  scripts/python_test.py
  src/infiniop/ops/attention/attention.h
  src/infiniop/ops/attention/operator.cc
  src/infiniop/ops/causal_softmax/cpu/causal_softmax_cpu.cc
  src/infiniop/reduce/cuda/reduce.cuh
  src/infiniop/tensor.h
  src/infiniop/tensor_descriptor.cc
  test/infiniop/attention.py
Labels: 紧急！, 类型：开发, 需要修改, 模块：算子

#196 issue/180：添加clip算子
  include/infiniop.h
  include/infiniop/ops/clip.h
  include/infiniop/ops/mul.h
  src/infiniop-test/include/ops.hpp
  src/infiniop-test/src/ops/clip.cpp
  src/infiniop/ops/clip/cpu/clip_cpu.cc
  src/infiniop/ops/clip/cpu/clip_cpu.h
  src/infiniop/ops/clip/cuda/clip_cuda.cu
  src/infiniop/ops/clip/cuda/clip_cuda.cuh
  src/infiniop/ops/clip/cuda/clip_cuda_internal.cuh
  src/infiniop/ops/clip/operator.cc
  test/infiniop-test/test_generate/testcases/clip.py
  test/infiniop/clip.py
Labels: 类型：开发, 准备好了, 模块：算子
