Repository InfiniTensor/InfiniCore, pull requests merged in 2025-04, with the labels that each got.

#59 issue/7: rmsnorm算子-昇腾
  src/infiniop/devices/ascend/common_ascend.cc
  src/infiniop/devices/ascend/common_ascend.h
  src/infiniop/ops/rms_norm/ascend/rms_norm_aclnn.cc
  src/infiniop/ops/rms_norm/ascend/rms_norm_aclnn.h
  src/infiniop/ops/rms_norm/operator.cc
  src/infiniop/ops/rms_norm/rms_norm.h
  xmake/ascend.lua
Labels: 类型：开发, 准备好了, 模块：算子

#122 issue/121/feat: 添加 Result 类型
  src/infiniop/ops/causal_softmax/causal_softmax.h
  src/infiniop/ops/causal_softmax/cpu/causal_softmax_cpu.cc
  src/infiniop/ops/causal_softmax/info.h
  src/infiniop/ops/gemm/ascend/gemm_ascend.cc
  src/infiniop/ops/gemm/bang/gemm_bang.cc
  src/infiniop/ops/gemm/blas.h
  src/infiniop/ops/gemm/cpu/gemm_cpu.cc
  src/infiniop/ops/gemm/cuda/gemm_cuda.cu
  src/infiniop/ops/gemm/gemm.h
  src/infiniop/ops/gemm/info.h
  src/infiniop/ops/gemm/kunlun/gemm_kunlun.cc
  src/infiniop/ops/gemm/maca/gemm_maca.cc
  src/infiniop/ops/gemm/operator.cc
  src/infiniop/ops/rearrange/cpu/rearrange_cpu.cc
  src/infiniop/ops/rms_norm/cpu/rms_norm_cpu.cc
  src/infiniop/ops/rms_norm/info.h
  src/infiniop/ops/rms_norm/rms_norm.h
  src/utils.h
  src/utils/rearrange.cc
  src/utils/rearrange.h
  src/utils/result.hpp
Labels: 紧急！, 类型：开发, 准备好了, 类型：重构

#138 issue/134 添加一键安装脚本
  .github/workflows/build.yml
  README.md
  include/infinicore.h
  scripts/install.bat
  scripts/install.sh
  src/utils.h
  xmake/test.lua
Labels: 紧急！, 类型：开发, 准备好了, 类型：测试

#102 issue/87:增加摩尔线程平台的handle
  src/infiniop/devices/handle.cc
  src/infiniop/devices/musa/common_musa.h
  src/infiniop/devices/musa/musa_handle.cc
  src/infiniop/devices/musa/musa_handle.h
  src/infiniop/devices/pool.h
  src/infiniop/ops/gemm/musa/gemm_musa.h
  src/infiniop/ops/gemm/musa/gemm_musa.mu
  src/infiniop/ops/gemm/operator.cc
  src/infinirt/musa/infinirt_musa.cc
  src/infinirt/musa/infinirt_musa.h
  test/infiniop/libinfiniop/utils.py
  xmake.lua
  xmake/musa.lua
Labels: 准备好了, 类型：重构

#143 issue/121/fix: 修改 cuda 和昇腾的 rms norm
  src/infiniop/ops/rms_norm/ascend/rms_norm_aclnn.cc
  src/infiniop/ops/rms_norm/cuda/rms_norm_cuda.cu
Labels: 准备好了, 类型：BUG, 模块：算子

#145 publish: add LICENSE
  LICENSE
Labels: 准备好了

#147 issue/134/refactor CI使用统一python脚本
  .github/workflows/build.yml
  README.md
  scripts/install.bat
  scripts/install.py
  scripts/install.sh
  scripts/python_test.py
  scripts/set_env.py
Labels: 紧急！, 准备好了

#151 issue/121/feat: 摩尔跟随Result类型修改Gemm构造流程
  src/infiniop/ops/gemm/musa/gemm_musa.mu
Labels: 紧急！, 准备好了

#162 issue/161 rope和causal softmax支持非原地
  include/infiniop.h
  include/infiniop/ops/causal_softmax.h
  include/infiniop/ops/rope.h
  src/infiniop/ops/causal_softmax/causal_softmax.h
  src/infiniop/ops/causal_softmax/cpu/causal_softmax_cpu.cc
  src/infiniop/ops/causal_softmax/info.h
  src/infiniop/ops/causal_softmax/operator.cc
  src/infiniop/ops/rope/operator.cc
  src/infiniop/ops/swiglu/cpu/swiglu_cpu.cc
  src/utils/check.h
  test/infiniop/causal_softmax.py
  test/infiniop/rope.py
Labels: 紧急！, 准备好了, 类型：重构, 模块：算子

#125 issue/4 添加cuda causal softmax算子
  src/infiniop/ops/causal_softmax/cuda/causal_softmax_cuda.cu
  src/infiniop/ops/causal_softmax/cuda/causal_softmax_cuda.cuh
  src/infiniop/ops/causal_softmax/cuda/causal_softmax_kernel.cuh
  src/infiniop/ops/causal_softmax/operator.cc
  src/infiniop/reduce/cuda/reduce.cuh
  xmake.lua
Labels: 类型：开发, 准备好了, 模块：算子

#136 issue/111: 添加rmsnorm以及算子编译流程
  src/infiniop/devices/kunlun/kunlun_common.h
  src/infiniop/ops/rms_norm/kunlun/rms_norm_kernel.xpu
  src/infiniop/ops/rms_norm/kunlun/rms_norm_kunlun.cc
  src/infiniop/ops/rms_norm/kunlun/rms_norm_kunlun.h
  src/infiniop/ops/rms_norm/operator.cc
  src/infiniop/reduce/kunlun/reduce_kunlun.h
  xmake/kunlun.lua
Labels: 类型：开发, 准备好了, 模块：算子, 模块：运行时

#155 issue/32: 实现摩尔线程rms_norm算子
  src/infiniop/devices/cuda/cuda_common.cuh
  src/infiniop/devices/cuda/cuda_kernel_common.cuh
  src/infiniop/devices/musa/common_musa.h
  src/infiniop/devices/musa/musa_handle.cc
  src/infiniop/ops/causal_softmax/cuda/causal_softmax_cuda.cu
  src/infiniop/ops/causal_softmax/cuda/causal_softmax_kernel.cuh
  src/infiniop/ops/rms_norm/cuda/rms_norm_kernel.cuh
  src/infiniop/ops/rms_norm/musa/rms_norm_musa.cuh
  src/infiniop/ops/rms_norm/musa/rms_norm_musa.mu
  src/infiniop/ops/rms_norm/operator.cc
  src/infinirt/infinirt.cc
Labels: 准备好了, 模块：算子

#132 issue/130: GEMM算子CPU平台的omp重构
  src/infiniop/ops/gemm/cpu/gemm_cpu.cc
Labels: 准备好了, 类型：重构, 模块：算子

#160 issue/40: 实现沐曦rms_norm算子
  src/infiniop/devices/maca/common_maca.h
  src/infiniop/devices/maca/maca_handle.cc
  src/infiniop/ops/rms_norm/maca/rms_norm_maca.cuh
  src/infiniop/ops/rms_norm/maca/rms_norm_maca.maca
  src/infiniop/ops/rms_norm/operator.cc
  xmake/maca.lua
Labels: 准备好了, 模块：算子

#169 Issue/48 Rope CPU & CUDA
  scripts/python_test.py
  src/infiniop/ops/rope/cpu/rope_cpu.cc
  src/infiniop/ops/rope/cpu/rope_cpu.h
  src/infiniop/ops/rope/cuda/rope_cuda.cu
  src/infiniop/ops/rope/cuda/rope_cuda.cuh
  src/infiniop/ops/rope/cuda/rope_cuda_kernel.cuh
  src/infiniop/ops/rope/operator.cc
  src/infiniop/ops/rope/rope.h
  src/utils/check.h
  test/infiniop/libinfiniop/utils.py
  test/infiniop/rope.py
Labels: 类型：开发, 准备好了, 模块：算子

#64 issue/8: causalsoftmax算子-昇腾
  src/infiniop/devices/ascend/common_ascend.cc
  src/infiniop/ops/causal_softmax/ascend/causal_softmax_aclnn.cc
  src/infiniop/ops/causal_softmax/ascend/causal_softmax_aclnn.h
  src/infiniop/ops/causal_softmax/operator.cc
  src/infiniop/ops/swiglu/operator.cc
  test/infiniop/causal_softmax.py
Labels: 类型：开发, 准备好了, 模块：算子

#149 添加swiglu算子测例
  src/infiniop-test/include/ops.hpp
  src/infiniop-test/src/ops/swiglu.cpp
  test/infiniop-test/test_generate/testcases/swiglu.py
Labels: 准备好了, 类型：测试

#190 issue/189/docs: update README.md
  README.md
Labels: 准备好了, 类型：文档

#198 issue/197/fix 修复rope cuda算子中dimx使用uint32_t代替unsigned int
  src/infiniop/ops/rope/cuda/rope_cuda.cu
Labels: 紧急！, 准备好了, 类型：BUG

#195 issue/194/fix: Fix ElementwiseInfo Meta Allocation
  src/infiniop/elementwise/cpu/elementwise_cpu.h
  src/infiniop/elementwise/elementwise.h
  src/infiniop/ops/swiglu/cuda/swiglu_cuda_internal.cuh
Labels: 准备好了, 类型：BUG

#173 issue/172 Add 算子 CPU & CUDA
  include/infiniop/ops/add.h
  scripts/python_test.py
  src/infiniop/elementwise/cuda/elementwise_cuda.cuh
  src/infiniop/ops/add/cpu/add_cpu.cc
  src/infiniop/ops/add/cpu/add_cpu.h
  src/infiniop/ops/add/cuda/add_cuda.cu
  src/infiniop/ops/add/cuda/add_cuda.cuh
  src/infiniop/ops/add/cuda/add_cuda_internal.cuh
  src/infiniop/ops/add/operator.cc
  test/infiniop/add.py
Labels: 类型：开发, 准备好了, 模块：算子

#199 修复昇腾调用aclSetAclOpExecutorRepeatable的潜在危险
  src/infiniop/ops/causal_softmax/ascend/causal_softmax_aclnn.cc
  src/infiniop/ops/gemm/ascend/gemm_ascend.cc
  src/infiniop/ops/rms_norm/ascend/rms_norm_aclnn.cc
Labels: 紧急！, 准备好了, 类型：BUG, 模块：算子

#201 Issue/200/fix: Updata FP16 and FP32 Tolerance for Add and SwiGLU
  test/infiniop/add.py
  test/infiniop/swiglu.py
Labels: 准备好了, 类型：BUG

#188 Issue/183 Mul算子CPU&CUDA
  include/infiniop.h
  include/infiniop/ops/mul.h
  src/infiniop-test/include/ops.hpp
  src/infiniop-test/src/ops/mul.cpp
  src/infiniop/ops/mul/cpu/mul_cpu.cc
  src/infiniop/ops/mul/cpu/mul_cpu.h
  src/infiniop/ops/mul/cuda/mul_cuda.cu
  src/infiniop/ops/mul/cuda/mul_cuda.cuh
  src/infiniop/ops/mul/cuda/mul_cuda_internal.cuh
  src/infiniop/ops/mul/operator.cc
  test/infiniop-test/test_generate/testcases/mul.py
  test/infiniop/mul.py
Labels: 类型：开发, 准备好了, 模块：算子
