Repository InfiniTensor/InfiniCore, pull requests merged in 2025-08, with the labels that each got.

#350 issue/349 P800 add
  src/infiniop/ops/add/kunlun/add_kunlun.h
  src/infiniop/ops/add/kunlun/add_kunlun.xpu
  src/infiniop/ops/add/kunlun/kernel.h
  src/infiniop/ops/add/operator.cc
Labels: 准备好了, 模块：算子

#319 Add scripts to generate gguf test cases for Question 2.
  test/infiniop-test/test_generate/testcases/cross_entropy_loss_backward.py
  test/infiniop-test/test_generate/testcases/div.py
  test/infiniop-test/test_generate/testcases/equal.py
  test/infiniop-test/test_generate/testcases/gelu.py
  test/infiniop-test/test_generate/testcases/gelu_backward.py
  test/infiniop-test/test_generate/testcases/logical_and.py
  test/infiniop-test/test_generate/testcases/logical_or.py
  test/infiniop-test/test_generate/testcases/relu_backward.py
  test/infiniop-test/test_generate/testcases/silu.py
Labels: 紧急！, 需要修改

#352 issue/349 P800 elementwise sub mul clip
  src/infiniop/elementwise/kunlun/elementwise_kunlun.h
  src/infiniop/ops/clip/kunlun/clip_kunlun.h
  src/infiniop/ops/clip/kunlun/clip_kunlun.xpu
  src/infiniop/ops/clip/kunlun/kernel.h
  src/infiniop/ops/clip/operator.cc
  src/infiniop/ops/mul/kunlun/kernel.h
  src/infiniop/ops/mul/kunlun/mul_kunlun.h
  src/infiniop/ops/mul/kunlun/mul_kunlun.xpu
  src/infiniop/ops/mul/operator.cc
  src/infiniop/ops/sub/kunlun/kernel.h
  src/infiniop/ops/sub/kunlun/sub_kunlun.h
  src/infiniop/ops/sub/kunlun/sub_kunlun.xpu
  src/infiniop/ops/sub/operator.cc
Labels: 类型：开发, 准备好了, 模块：算子

#366 issue/365 - fixing an interface mismatch
  test/infiniop/libinfiniop/utils.py
Labels: 准备好了, 类型：BUG

#250 issue/246: add Elementwise and SwiGLU in moore gpu
  src/infiniop/devices/moore/moore_kernel_common.h
  src/infiniop/elementwise/moore/elementwise_moore.h
  src/infiniop/elementwise/moore/elementwise_moore_api.h
  src/infiniop/ops/swiglu/moore/siwglu_moore_kernel.h
  src/infiniop/ops/swiglu/moore/swiglu_moore.h
  src/infiniop/ops/swiglu/moore/swiglu_moore.mu
  src/infiniop/ops/swiglu/operator.cc
Labels: 准备好了, 模块：算子

#364 Issue/240 - Cambricon Reduce
  src/infiniop-test/src/main.cpp
  src/infiniop/ops/causal_softmax/bang/causal_softmax_bang.h
  src/infiniop/ops/causal_softmax/bang/causal_softmax_bang.mlu
  src/infiniop/ops/causal_softmax/operator.cc
  src/infiniop/ops/rms_norm/bang/rms_norm_bang.h
  src/infiniop/ops/rms_norm/bang/rms_norm_bang.mlu
  src/infiniop/ops/rms_norm/operator.cc
  src/infiniop/reduce/bang/reduce_bang.h
  test/infiniop/causal_softmax.py
  test/infiniop/rms_norm.py
Labels: 类型：开发, 准备好了, 模块：算子

#363 issue/362 - allowed bfloat16_t for cambricon gemm
  src/infiniop/ops/gemm/bang/gemm_bang.cc
Labels: 类型：开发, 准备好了, 模块：算子

#266 issue/265 - Implemented the RoPE operator for Cambricon Bang
  src/infiniop/ops/rope/bang/rope_bang.h
  src/infiniop/ops/rope/bang/rope_bang.mlu
  src/infiniop/ops/rope/bang/rope_bang_kernel.mlu
  src/infiniop/ops/rope/operator.cc
Labels: 类型：开发, 准备好了, 模块：算子

#301 issue/300 - InfiniCCL Cambricon
  src/infiniccl/cambricon/infiniccl_cambricon.cc
  src/infiniccl/cambricon/infiniccl_cambricon.h
  src/infiniccl/infiniccl.cc
  src/infinirt/bang/infinirt_bang.cc
  xmake.lua
  xmake/bang.lua
Labels: 类型：开发, 准备好了, 模块：通信

#386 Issue/385 p800 上rmsnorm重构，支持多精度
  src/infiniop/devices/kunlun/kunlun_kernel_common.h
  src/infiniop/ops/rms_norm/kunlun/kernel.h
  src/infiniop/ops/rms_norm/kunlun/rms_norm_kernel.xpu
  src/infiniop/ops/rms_norm/kunlun/rms_norm_kunlun.cc
  src/infiniop/ops/rms_norm/kunlun/rms_norm_kunlun.h
  src/infiniop/ops/rms_norm/kunlun/rms_norm_kunlun.xpu
  src/infiniop/reduce/kunlun/reduce_kunlun.h
Labels: 类型：开发, 准备好了, 模块：算子

#182 issue/163: 昆仑芯平台rope算子重构
  src/infiniop/ops/rope/kunlun/rope_kunlun.h
  src/infiniop/ops/rope/kunlun/rope_kunlun.xpu
  src/infiniop/ops/rope/operator.cc
Labels: 类型：开发, 准备好了, 类型：重构, 模块：算子

#389 issue/388: Support 3D Cases for RMS Norm
  src/infiniop/ops/rms_norm/cpu/rms_norm_cpu.cc
  src/infiniop/ops/rms_norm/cuda/kernel.cuh
  src/infiniop/ops/rms_norm/info.h
  src/infiniop/ops/rms_norm/metax/rms_norm_metax.maca
  src/infiniop/ops/rms_norm/moore/rms_norm_moore.mu
  src/infiniop/ops/rms_norm/nvidia/rms_norm_nvidia.cu
  test/infiniop-test/test_generate/testcases/rms_norm.py
  test/infiniop/rms_norm.py
Labels: 类型：开发, 准备好了, 模块：算子

#408 issue/406: 修复 isMergable 的 stride 检查逻辑
  src/infiniop/tensor_descriptor.cc
Labels: 准备好了, 类型：BUG

#412 issue/411: adjust mudnn handle use to prevent mudnn handle mismatching
  src/infiniop/devices/moore/moore_common.h
  src/infiniop/devices/moore/moore_handle.cc
Labels: 类型：BUG
