Repository InfiniTensor/InfiniCore, pull requests merged in 2025-02, with the labels that each got.

#27 issue1: New Optimized Matmul Test
  test/infiniop/libinfiniop/devices.py
  test/infiniop/libinfiniop/utils.py
  test/infiniop/matmul.py
  test/infiniop/test_utils.py
Labels: 准备好了, 模块：算子, 类型：测试

#45 issue/52 代码格式化：机制和效果
  .clang-format
  .github/workflows/build.yml
  README.md
  include/infinicore.h
  include/infiniop/ops/causal_softmax.h
  include/infiniop/ops/conv.h
  include/infiniop/ops/random_sample.h
  include/infiniop/tensor_descriptor.h
  scripts/format.py
  src/infiniop/devices/ascend/common_ascend.cc
  src/infiniop/devices/ascend/common_ascend.h
  src/infiniop/devices/ascend/tensor_aclnn.cc
  src/infiniop/devices/cpu/common_cpu.cc
  src/infiniop/devices/cpu/common_cpu.h
  src/infiniop/devices/cuda/common_cuda.cuh
  src/infiniop/devices/pool.h
  src/infiniop/ops/causal_softmax/operator.cc
  src/infiniop/ops/matmul/ascend/matmul_aclnn.cc
  src/infiniop/ops/matmul/bang/matmul_cnnl.cc
  src/infiniop/ops/matmul/blas.h
  src/infiniop/ops/matmul/cpu/matmul_cpu.cc
  src/infiniop/ops/matmul/cuda/matmul_cuda.cu
  src/infiniop/ops/matmul/cuda/matmul_cuda.cuh
  src/infiniop/ops/matmul/cuda/matmul_cuda_api.h
  src/infiniop/ops/matmul/cuda/matmul_cuda_kernel.cu
  src/infiniop/ops/random_sample/operator.cc
  src/infiniop/ops/rearrange/operator.cc
  src/infiniop/ops/rms_norm/operator.cc
  src/infiniop/ops/utils.h
  test/infiniop/__init__.py
  test/infiniop/add.py
  test/infiniop/avg_pool.py
  test/infiniop/causal_softmax.py
  test/infiniop/conv.py
  test/infiniop/expand.py
  test/infiniop/gemm.py
  test/infiniop/global_avg_pool.py
  test/infiniop/libinfiniop/__init__.py
  test/infiniop/libinfiniop/datatypes.py
  test/infiniop/libinfiniop/utils.py
  test/infiniop/matmul.py
  test/infiniop/max_pool.py
  test/infiniop/random_sample.py
  test/infiniop/rearrange.py
  test/infiniop/relu.py
  test/infiniop/rms_norm.py
  test/infiniop/rotary_embedding.py
  test/infiniop/swiglu.py
Labels: 紧急！, 准备好了

#56 issue/55: CI 在 Windows 上执行
  .github/workflows/build.yml
  xmake.lua
  xmake/cpu.lua
Labels: 紧急！, 类型：开发, 准备好了

#70 Issue/69 增加运行时接口
  include/infinicore.h
  include/infiniop.h
  include/infinirt.h
Labels: 紧急！, 类型：开发, 准备好了, 模块：运行时

#67 issue/66: 重构7个算子的测试脚本
  test/infiniop/causal_softmax.py
  test/infiniop/random_sample.py
  test/infiniop/rearrange.py
  test/infiniop/rms_norm.py
  test/infiniop/rotary_embedding.py
  test/infiniop/swiglu.py
Labels: 紧急！, 类型：重构

#65 issue/63 重构算子定义文件结构及风格修改
  include/infiniop/handle.h
  include/infiniop/operator.h
  include/infiniop/ops/attention.h
  include/infiniop/ops/mlp.h
  include/infiniop/tensor_descriptor.h
  scripts/format.py
  src/infiniop/devices/ascend/tensor_aclnn.h
  src/infiniop/devices/cpu/common_cpu.cc
  src/infiniop/devices/cpu/common_cpu.h
  src/infiniop/devices/cpu/cpu_handle.cc
  src/infiniop/devices/cuda/common_cuda.cuh
  src/infiniop/devices/cuda/cuda_handle.cu
  src/infiniop/devices/handle.cc
  src/infiniop/operator.cc
  src/infiniop/ops/causal_softmax/operator.cc
  src/infiniop/ops/matmul/ascend/matmul_aclnn.cc
  src/infiniop/ops/matmul/ascend/matmul_aclnn.h
  src/infiniop/ops/matmul/ascend/matmul_aclnn_api.h
  src/infiniop/ops/matmul/ascend/matmul_ascend.cc
  src/infiniop/ops/matmul/ascend/matmul_ascend.h
  src/infiniop/ops/matmul/bang/matmul_bang.cc
  src/infiniop/ops/matmul/bang/matmul_bang.h
  src/infiniop/ops/matmul/bang/matmul_cnnl.cc
  src/infiniop/ops/matmul/bang/matmul_cnnl.h
  src/infiniop/ops/matmul/bang/matmul_cnnl_api.h
  src/infiniop/ops/matmul/blas.h
  src/infiniop/ops/matmul/cpu/matmul_cpu.cc
  src/infiniop/ops/matmul/cpu/matmul_cpu.h
  src/infiniop/ops/matmul/cpu/matmul_cpu_api.h
  src/infiniop/ops/matmul/cuda/matmul_cuda.cu
  src/infiniop/ops/matmul/cuda/matmul_cuda.cuh
  src/infiniop/ops/matmul/cuda/matmul_cuda_api.h
  src/infiniop/ops/matmul/cuda/matmul_cuda_kernel.cu
  src/infiniop/ops/matmul/matmul.h
  src/infiniop/ops/matmul/operator.cc
  src/infiniop/ops/random_sample/operator.cc
  src/infiniop/ops/rearrange/operator.cc
  src/infiniop/ops/rms_norm/operator.cc
  src/infiniop/ops/rotary_embedding/operator.cc
  src/infiniop/ops/swiglu/operator.cc
Labels: 紧急！, 准备好了, 类型：重构

#75 issue/74 Fix Inplace, Naming, and Reference Issues in Tests
  test/infiniop/libinfiniop/utils.py
  test/infiniop/random_sample.py
  test/infiniop/rearrange.py
  test/infiniop/rms_norm.py
  test/infiniop/rotary_embedding.py
  test/infiniop/swiglu.py
Labels: 准备好了, 类型：BUG, 类型：测试

#26 issue/25：昆仑芯 matmul
  src/infiniop/devices/handle.cc
  src/infiniop/devices/kunlun/common_kunlun.h
  src/infiniop/devices/kunlun/kunlun_handle.cc
  src/infiniop/devices/kunlun/kunlun_handle.h
  src/infiniop/ops/matmul/kunlun/matmul_kunlun.cc
  src/infiniop/ops/matmul/kunlun/matmul_kunlun.h
  src/infiniop/ops/matmul/operator.cc
  test/infiniop/libinfiniop/utils.py
  xmake.lua
  xmake/kunlun.lua
Labels: 准备好了, 模块：算子
